# Generated by Django 3.2.3 on 2021-05-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dim_entry_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dim_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_lat', models.FloatField()),
                ('node_lon', models.FloatField()),
                ('node_status', models.IntegerField(verbose_name=1)),
            ],
        ),
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('hpno', models.CharField(max_length=12)),
                ('occupants', models.IntegerField(verbose_name=2)),
                ('danger', models.BooleanField()),
                ('water', models.BooleanField()),
                ('food', models.BooleanField()),
                ('hug', models.BooleanField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dim_node')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dim_entry_status')),
            ],
        ),
    ]
