# Generated by Django 3.2.3 on 2021-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='dim_node',
            name='node_desc',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
